### PR TITLE
Fix rbc command to accept project with no spec

### LINKED ISSUE #2874: jf rbc (release-bundle-create) is not working when using Artifactory projects
### Describe the bug

```
root@e81d0d54be2c:/# jf rbc --signing-key=default-gpg-key --project gbq GBQ-$MODULE $BASE_REV 
16:04:05 [🔵Info] Trace ID for JFrog Platform logs: cde0227c30537ed3
16:04:05 [🚨Error] server response: 404 Not Found
{
  "errors": [
    {
      "status": 404,
      "message": "Build not found, name: local-gbq-test-dev, number: 12, repository: artifactory-build-info, started: null"
    }
  ]
}

root@e81d0d54be2c:/# env |sort | grep JFROG
JFROG_CLI_BUILD_NAME=local-gbq-test-dev
JFROG_CLI_BUILD_NUMBER=12
JFROG_CLI_BUILD_PROJECT=gbq

root@e81d0d54be2c:/# jf -v
jf version 2.73.3
```

It should use qbq-build-info instead of artifactory-build-info. It seems that it ignores project info

I tried to use parameters
`--build-name=local-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME --build-number=$CI_JOB_ID --project=$JF_PROJECT`
but then `--project` is ignored too!

I tried to find similar issues, but I've only found that there was similar issue in the past that --project was ignored in multiple cli commands.

### Current behavior

jf rbc command ignores --project and/or JFROG_CLI_BUILD_PROJECT.
It searchs build info in artifactory-build-info repository instead of project-build-info repository

### Reproduction steps

Step to reproduce
1. Run ubuntu docker
2. Execute scripts
```
apt-get update
apt-get upgrade -y
apt-get install -y curl zip

JFROG_PLATFORM_SERVER_ID=myArtifactory
JFROG_PLATFORM_URL=https://address.jfrog.io
JFROG_PLATFORM_USER=user
JFROG_PLATFORM_PASS=pass

CI_PROJECT_NAME=gbq-test
CI_COMMIT_REF_NAME=dev
CI_JOB_ID=12

ORG_PATH=com/company
MODULE=SDK
BASE_REV=1.0.0

TARGET_REPO=gbq-generic-dev-local
JF_PROJECT=gbq

# Install JFrog CLI
curl -fL https://install-cli.jfrog.io | sh
# Configure Artifactory server
jf config add $JFROG_PLATFORM_SERVER_ID --url=$JFROG_PLATFORM_URL --user=$JFROG_PLATFORM_USER --password=$JFROG_PLATFORM_PASS --interactive=false
# Ping artifactory
jf rt ping

#BUILD
echo "test $CI_JOB_ID" >> test.txt
zip $MODULE-$BASE_REV+$CI_JOB_ID.zip test.txt

# DEPLOY
jf rt u --project $JF_PROJECT --build-name local-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME --build-number $CI_JOB_ID $MODULE-$BASE_REV+$CI_JOB_ID.zip $TARGET_REPO/$ORG_PATH/$MODULE/$MODULE-$BASE_REV.zip 

# Publish the build info to Artifactory:
jf rt bp --project $JF_PROJECT local-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME $CI_JOB_ID 

# Create a release bundle
export JFROG_CLI_BUILD_PROJECT=gbq
export JFROG_CLI_BUILD_NAME=local-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME
export JFROG_CLI_BUILD_NUMBER=$CI_JOB_ID
jf rbc --signing-key=default-gpg-key GBQ-$MODULE $BASE_REV 
```

### Expected behavior

I'd like to use jf rbc command to create release bundle using projects in artifactory

### JFrog CLI version

2.73.3

### Operating system type and version

Ubuntu 24.04.2 LTS

### JFrog Artifactory version

Cloud

### JFrog Xray version

_No response_

### PR DESCRIPTION
**Pull request by bhanurp**
- [x] All [tests](https://github.com/jfrog/jfrog-cli/CONTRIBUTING.md#tests) have passed. If this feature is not already covered by the tests, new tests have been added.
- [x] The pull request is targeting the `dev` branch.
- [x] The code has been validated to compile successfully by running `go vet ./...`.
- [x] The code has been formatted properly using `go fmt ./...`.

---
## Depends On
https://github.com/jfrog/jfrog-cli-core/pull/1356
---
Fixes #2874

### CODE REVIEW

File: lifecycle/cli.go [hunk 1]
```diff
@@ -222,7 +222,7 @@ func getReleaseBundleCreationSpec(c *cli.Context) (*spec.SpecFiles, error) {
 	buildNumber := getStringFlagOrEnv(c, cliutils.BuildNumber, coreutils.BuildNumber)
 
 	if buildName != "" && buildNumber != "" {
-		return speccore.CreateSpecFromBuildNameAndNumber(buildName, buildNumber)
+		return speccore.CreateSpecFromBuildNameAndNumber(buildName, buildNumber, cliutils.GetProject(c))
```
Comment (EyalDelarea) [inline lifecycle/cli.go:225]: Great!
Let's just add e2e tests to verify the reales bundle is being created at the right project

**Review by EyalDelarea — CHANGES_REQUESTED** [review]

File: lifecycle/cli.go (hunk 1 above)
Comment (bhanurp) [reply lifecycle/cli.go]: added new test `TestCreateBundleWithoutSpecAndWithProject`
